### PR TITLE
big refactor! 

### PR DESCRIPTION
**Pull request by TheJaysH**
add support for block tags, using native config api, fixed bug with diagonals.

### CODE REVIEW

**Comment by TheJaysH** [comment]
Let me know if you have any questions

**Comment by TheJaysH** [comment]
Any updates on this?

**Comment by altaiiiir** [comment]
Thanks for your contribution!! Also, congrats on your first contribution:)

I'll be taking a look at this today.

**Review by altaiiiir — APPROVED** [review]
Thanks for this PR. Definitely loved the new organization and addition of tags. Taught me a lot about Minecraft modding from reading this code. 

I did discover a couple of bugs but I believe these were present even before your refactor so, I'll work on fixing those after merging your PR. 

Approved!

**Pull request merged**
